/* eslint-disable @typescript-eslint/explicit-function-return-type */
'use client';

import * as React from 'react';
import { useParams } from 'next/navigation';
import Avatar from '@mui/material/Avatar';
import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import Grid from '@mui/material/Grid';
import Stack from '@mui/material/Stack';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import Chip from '@mui/material/Chip';
import Divider from '@mui/material/Divider';
import { ArrowLeft as ArrowLeftIcon } from '@phosphor-icons/react/dist/ssr/ArrowLeft';
import { TrendUp as TrendUpIcon } from '@phosphor-icons/react/dist/ssr/TrendUp';
import { TrendDown as TrendDownIcon } from '@phosphor-icons/react/dist/ssr/TrendDown';
import { Download as DownloadIcon } from '@phosphor-icons/react/dist/ssr/Download';

const empresasData = {
  // EMPRESAS EXISTENTES - NÃO REMOVER
  'PETR4': {
    ticker: 'PETR4',
    nomeCompleto: 'Petróleo Brasileiro S.A. - Petrobras',
    setor: 'Petróleo, Gás e Biocombustíveis',
    descricao: 'A Petrobras é uma empresa de energia, focada em óleo, gás natural e energia de baixo carbono.',
    avatar: 'https://www.ivalor.com.br/media/emp/logos/PETR.png',
    precoAtual: 'R$ 38,47',
    variacao: '+2.3%',
    tendencia: 'up',
    dataEntrada: '15/03/2022',
    precoIniciou: 'R$ 28,90',
    dy: '18.4%',
    precoTeto: 'R$ 45,00',
    viesAtual: 'Compra',
    variacaoHoje: '+1.8%',
    rendProventos: '+24.7%',
    ibovespaEpoca: '112.200',
    ibovespaVariacao: '+18.2%',
    percentualCarteira: '12.5%',
    marketCap: 'R$ 512,8 bi',
    pl: '3.8',
    pvp: '1.2',
    roe: '31.5%',
    relatorios: [
      { nome: 'Relatório Anual 2023', data: '2024-03-15', url: '#' },
      { nome: 'Balanço Q4 2023', data: '2024-02-28', url: '#' },
    ],
    proventos: [
      { tipo: 'Dividendo', valor: 'R$ 2,15', dataEx: '15/06/2024', dataPagamento: '29/06/2024', status: 'Aprovado' },
      { tipo: 'JCP', valor: 'R$ 1,85', dataEx: '15/03/2024', dataPagamento: '28/03/2024', status: 'Pago' },
    ]
  },
  'DEXP3': {
    ticker: 'DEXP3',
    nomeCompleto: 'Dexxos Participações S.A.',
    setor: 'Nanocap/Químico',
    descricao: 'Empresa especializada em soluções químicas inovadoras.',
    avatar: 'https://www.ivalor.com.br/media/emp/logos/DEXP.png',
    precoAtual: 'R$ 9,33',
    variacao: '+5.9%',
    tendencia: 'up',
    dataEntrada: '27/01/2023',
    precoIniciou: 'R$ 7,96',
    dy: '5.91%',
    precoTeto: 'R$ 13,10',
    viesAtual: 'Compra',
    variacaoHoje: '+3.2%',
    rendProventos: '+17.2%',
    ibovespaEpoca: '108.500',
    ibovespaVariacao: '+19.1%',
    percentualCarteira: '8.7%',
    marketCap: 'R$ 1,2 bi',
    pl: '12.3',
    pvp: '0.8',
    roe: '15.2%',
    relatorios: [
      { nome: 'Relatório Anual 2023', data: '2024-03-10', url: '#' },
    ],
    proventos: [
      { tipo: 'Dividendo', valor: 'R$ 0,42', dataEx: '15/05/2024', dataPagamento: '30/05/2024', status: 'Aprovado' },
      { tipo: 'JCP', valor: 'R$ 0,38', dataEx: '15/02/2024', dataPagamento: '28/02/2024', status: 'Pago' },
    ]
  },

  // NOVAS EMPRESAS - ADICIONAR ESTAS
  'ALOS3': {
    ticker: 'ALOS3',
    nomeCompleto: 'Alos Participações S.A.',
    setor: 'Shoppings',
    descricao: 'Empresa do setor de shoppings com foco em desenvolvimento imobiliário.',
    avatar: 'https://www.ivalor.com.br/media/emp/logos/ALOS.png',
    precoAtual: 'R$ 21,67',
    variacao: '-18.8%',
    tendencia: 'down',
    dataEntrada: '15/01/2021',
    precoIniciou: 'R$ 26,68',
    dy: '5,95%',
    precoTeto: 'R$ 23,76',
    viesAtual: 'Compra',
    variacaoHoje: '-1.2%',
    rendProventos: '+12.4%',
    ibovespaEpoca: '118.500',
    ibovespaVariacao: '+22.1%',
    percentualCarteira: '6.2%',
    marketCap: 'R$ 890M',
    pl: '15.2',
    pvp: '1.1',
    roe: '8.7%',
    relatorios: [
      { nome: 'Relatório Anual 2023', data: '2024-03-20', url: '#' },
    ],
    proventos: [
      { tipo: 'Dividendo', valor: 'R$ 1,29', dataEx: '15/04/2024', dataPagamento: '30/04/2024', status: 'Aprovado' },
    ]
  },
  'TUPY3': {
    ticker: 'TUPY3',
    nomeCompleto: 'Tupy S.A.',
    setor: 'Industrial',
    descricao: 'Líder mundial na fundição de ferro e alumínio para o setor automotivo.',
    avatar: 'https://www.ivalor.com.br/media/emp/logos/TUPY.png',
    precoAtual: 'R$ 18,93',
    variacao: '-7.0%',
    tendencia: 'down',
    dataEntrada: '04/11/2020',
    precoIniciou: 'R$ 20,36',
    dy: '1,71%',
    precoTeto: 'R$ 31,50',
    viesAtual: 'Compra',
    variacaoHoje: '+0.8%',
    rendProventos: '+8.9%',
    ibovespaEpoca: '103.200',
    ibovespaVariacao: '+41.2%',
    percentualCarteira: '4.8%',
    marketCap: 'R$ 2,1 bi',
    pl: '8.7',
    pvp: '0.9',
    roe: '12.1%',
    relatorios: [
      { nome: 'Relatório Anual 2023', data: '2024-03-15', url: '#' },
    ],
    proventos: [
      { tipo: 'Dividendo', valor: 'R$ 0,32', dataEx: '15/05/2024', dataPagamento: '30/05/2024', status: 'Aprovado' },
    ]
  },
  'RECV3': {
    ticker: 'RECV3',
    nomeCompleto: 'Petrorecôncavo S.A.',
    setor: 'Petróleo',
    descricao: 'Empresa de exploração e produção de petróleo e gás natural.',
    avatar: 'https://www.ivalor.com.br/media/emp/logos/RECV.png',
    precoAtual: 'R$ 13,97',
    variacao: '-37.3%',
    tendencia: 'down',
    dataEntrada: '23/07/2023',
    precoIniciou: 'R$ 22,29',
    dy: '11,07%',
    precoTeto: 'R$ 31,37',
    viesAtual: 'Compra',
    variacaoHoje: '-2.1%',
    rendProventos: '+15.8%',
    ibovespaEpoca: '119.800',
    ibovespaVariacao: '+20.8%',
    percentualCarteira: '7.3%',
    marketCap: 'R$ 3,2 bi',
    pl: '6.2',
    pvp: '0.7',
    roe: '22.4%',
    relatorios: [
      { nome: 'Relatório Anual 2023', data: '2024-03-10', url: '#' },
    ],
    proventos: [
      { tipo: 'Dividendo', valor: 'R$ 1,55', dataEx: '15/06/2024', dataPagamento: '30/06/2024', status: 'Aprovado' },
    ]
  },
  'CSED3': {
    ticker: 'CSED3',
    nomeCompleto: 'Cruzeiro do Sul Educacional S.A.',
    setor: 'Educação',
    descricao: 'Grupo educacional com foco em ensino superior e técnico.',
    avatar: 'https://www.ivalor.com.br/media/emp/logos/CSED.png',
    precoAtual: 'R$ 5,12',
    variacao: '+14.0%',
    tendencia: 'up',
    dataEntrada: '10/12/2023',
    precoIniciou: 'R$ 4,49',
    dy: '4,96%',
    precoTeto: 'R$ 8,35',
    viesAtual: 'Compra',
    variacaoHoje: '+2.1%',
    rendProventos: '+18.7%',
    ibovespaEpoca: '125.800',
    ibovespaVariacao: '+15.2%',
    percentualCarteira: '3.2%',
    marketCap: 'R$ 1,8 bi',
    pl: '9.8',
    pvp: '1.4',
    roe: '14.6%',
    relatorios: [
      { nome: 'Relatório Anual 2023', data: '2024-03-18', url: '#' },
    ],
    proventos: [
      { tipo: 'Dividendo', valor: 'R$ 0,25', dataEx: '15/07/2024', dataPagamento: '30/07/2024', status: 'Aprovado' },
    ]
  },
  'PRIO3': {
    ticker: 'PRIO3',
    nomeCompleto: 'PetroRio S.A.',
    setor: 'Petróleo',
    descricao: 'Empresa independente de exploração e produção de petróleo no Brasil.',
    avatar: 'https://www.ivalor.com.br/media/emp/logos/PRIO.png',
    precoAtual: 'R$ 38,80',
    variacao: '+66.2%',
    tendencia: 'up',
    dataEntrada: '04/08/2022',
    precoIniciou: 'R$ 23,35',
    dy: '0,18%',
    precoTeto: 'R$ 48,70',
    viesAtual: 'Compra',
    variacaoHoje: '+2.8%',
    rendProventos: '+72.5%',
    ibovespaEpoca: '107.500',
    ibovespaVariacao: '+35.1%',
    percentualCarteira: '9.1%',
    marketCap: 'R$ 5,1 bi',
    pl: '4.8',
    pvp: '1.3',
    roe: '28.7%',
    relatorios: [
      { nome: 'Relatório Anual 2023', data: '2024-03-25', url: '#' },
    ],
    proventos: [
      { tipo: 'Dividendo', valor: 'R$ 0,07', dataEx: '15/07/2024', dataPagamento: '30/07/2024', status: 'Aprovado' },
    ]
  },
  'RAPT4': {
    ticker: 'RAPT4',
    nomeCompleto: 'Randon S.A. Implementos e Participações',
    setor: 'Industrial',
    descricao: 'Fabricante de implementos rodoviários, peças e componentes automotivos.',
    avatar: 'https://www.ivalor.com.br/media/emp/logos/RAPT.png',
    precoAtual: 'R$ 8,25',
    variacao: '-50.5%',
    tendencia: 'down',
    dataEntrada: '16/09/2021',
    precoIniciou: 'R$ 16,69',
    dy: '4,80%',
    precoTeto: 'R$ 14,00',
    viesAtual: 'Compra',
    variacaoHoje: '-0.8%',
    rendProventos: '+8.2%',
    ibovespaEpoca: '114.200',
    ibovespaVariacao: '+27.8%',
    percentualCarteira: '2.8%',
    marketCap: 'R$ 1,4 bi',
    pl: '11.5',
    pvp: '0.6',
    roe: '5.8%',
    relatorios: [
      { nome: 'Relatório Anual 2023', data: '2024-03-12', url: '#' },
    ],
    proventos: [
      { tipo: 'Dividendo', valor: 'R$ 0,40', dataEx: '15/08/2024', dataPagamento: '30/08/2024', status: 'Aprovado' },
    ]
  },
  'SMTO3': {
    ticker: 'SMTO3',
    nomeCompleto: 'São Martinho S.A.',
    setor: 'Sucroenergético',
    descricao: 'Produtora de açúcar, etanol e energia elétrica a partir da cana-de-açúcar.',
    avatar: 'https://www.ivalor.com.br/media/emp/logos/SMTO.png',
    precoAtual: 'R$ 20,97',
    variacao: '-25.6%',
    tendencia: 'down',
    dataEntrada: '10/11/2022',
    precoIniciou: 'R$ 28,20',
    dy: '3,51%',
    precoTeto: 'R$ 35,00',
    viesAtual: 'Compra',
    variacaoHoje: '+1.5%',
    rendProventos: '+5.8%',
    ibovespaEpoca: '117.300',
    ibovespaVariacao: '+24.2%',
    percentualCarteira: '5.1%',
    marketCap: 'R$ 3,8 bi',
    pl: '8.9',
    pvp: '0.9',
    roe: '10.1%',
    relatorios: [
      { nome: 'Relatório Anual 2023', data: '2024-03-22', url: '#' },
    ],
    proventos: [
      { tipo: 'Dividendo', valor: 'R$ 0,74', dataEx: '15/09/2024', dataPagamento: '30/09/2024', status: 'Aprovado' },
    ]
  },
  'FESA4': {
    ticker: 'FESA4',
    nomeCompleto: 'Ferbasa S.A.',
    setor: 'Commodities',
    descricao: 'Produtora de ferro-ligas e produtos siderúrgicos especiais.',
    avatar: 'https://www.ivalor.com.br/media/emp/logos/FESA.png',
    precoAtual: 'R$ 6,92',
    variacao: '+54.1%',
    tendencia: 'up',
    dataEntrada: '11/12/2020',
    precoIniciou: 'R$ 4,49',
    dy: '5,68%',
    precoTeto: 'R$ 14,07',
    viesAtual: 'Compra',
    variacaoHoje: '+3.2%',
    rendProventos: '+68.4%',
    ibovespaEpoca: '119.000',
    ibovespaVariacao: '+22.5%',
    percentualCarteira: '4.2%',
    marketCap: 'R$ 780M',
    pl: '6.8',
    pvp: '0.7',
    roe: '12.8%',
    relatorios: [
      { nome: 'Relatório Anual 2023', data: '2024-03-08', url: '#' },
    ],
    proventos: [
      { tipo: 'Dividendo', valor: 'R$ 0,39', dataEx: '15/10/2024', dataPagamento: '30/10/2024', status: 'Aprovado' },
    ]
  },
  'UNIP6': {
    ticker: 'UNIP6',
    nomeCompleto: 'Unipar Carbocloro S.A.',
    setor: 'Químico',
    descricao: 'Produtora de cloro-soda e produtos petroquímicos básicos.',
    avatar: 'https://www.ivalor.com.br/media/emp/logos/UNIP.png',
    precoAtual: 'R$ 61,00',
    variacao: '+43.8%',
    tendencia: 'up',
    dataEntrada: '08/12/2020',
    precoIniciou: 'R$ 42,41',
    dy: '6,77%',
    precoTeto: 'R$ 117,90',
    viesAtual: 'Compra',
    variacaoHoje: '+1.8%',
    rendProventos: '+55.2%',
    ibovespaEpoca: '118.800',
    ibovespaVariacao: '+22.7%',
    percentualCarteira: '8.9%',
    marketCap: 'R$ 15,2 bi',
    pl: '7.2',
    pvp: '1.8',
    roe: '24.5%',
    relatorios: [
      { nome: 'Relatório Anual 2023', data: '2024-03-28', url: '#' },
    ],
    proventos: [
      { tipo: 'Dividendo', valor: 'R$ 4,13', dataEx: '15/11/2024', dataPagamento: '30/11/2024', status: 'Aprovado' },
    ]
  },
  'FLRY3': {
    ticker: 'FLRY3',
    nomeCompleto: 'Fleury S.A.',
    setor: 'Saúde',
    descricao: 'Rede de medicina diagnóstica e prestação de serviços de saúde.',
    avatar: 'https://www.ivalor.com.br/media/emp/logos/FLRY.png',
    precoAtual: 'R$ 12,59',
    variacao: '-13.9%',
    tendencia: 'down',
    dataEntrada: '19/05/2022',
    precoIniciou: 'R$ 14,63',
    dy: '5,20%',
    precoTeto: 'R$ 17,50',
    viesAtual: 'Compra',
    variacaoHoje: '-0.5%',
    rendProventos: '+7.8%',
    ibovespaEpoca: '113.500',
    ibovespaVariacao: '+28.4%',
    percentualCarteira: '3.8%',
    marketCap: 'R$ 6,8 bi',
    pl: '18.5',
    pvp: '1.5',
    roe: '8.1%',
    relatorios: [
      { nome: 'Relatório Anual 2023', data: '2024-03-14', url: '#' },
    ],
    proventos: [
      { tipo: 'Dividendo', valor: 'R$ 0,65', dataEx: '15/12/2024', dataPagamento: '30/12/2024', status: 'Aprovado' },
    ]
  },
  'EZTC3': {
    ticker: 'EZTC3',
    nomeCompleto: 'Eztec Empreendimentos e Participações S.A.',
    setor: 'Construção Civil',
    descricao: 'Construtora e incorporadora imobiliária focada no segmento residencial.',
    avatar: 'https://www.ivalor.com.br/media/emp/logos/EZTC.png',
    precoAtual: 'R$ 13,17',
    variacao: '-41.7%',
    tendencia: 'down',
    dataEntrada: '07/10/2022',
    precoIniciou: 'R$ 22,61',
    dy: '7,83%',
    precoTeto: 'R$ 30,00',
    viesAtual: 'Compra',
    variacaoHoje: '-1.2%',
    rendProventos: '+12.8%',
    ibovespaEpoca: '115.200',
    ibovespaVariacao: '+26.5%',
    percentualCarteira: '2.9%',
    marketCap: 'R$ 2,1 bi',
    pl: '9.8',
    pvp: '0.8',
    roe: '8.2%',
    relatorios: [
      { nome: 'Relatório Anual 2023', data: '2024-03-16', url: '#' },
    ],
    proventos: [
      { tipo: 'Dividendo', valor: 'R$ 1,03', dataEx: '15/01/2025', dataPagamento: '30/01/2025', status: 'Aprovado' },
    ]
  },
  'JALL3': {
    ticker: 'JALL3',
    nomeCompleto: 'Jalles Machado S.A.',
    setor: 'Sucroenergético',
    descricao: 'Produtora de açúcar, etanol e energia elétrica derivados da cana-de-açúcar.',
    avatar: 'https://www.ivalor.com.br/media/emp/logos/JALL.png',
    precoAtual: 'R$ 4,32',
    variacao: '-48.3%',
    tendencia: 'down',
    dataEntrada: '17/06/2022',
    precoIniciou: 'R$ 8,36',
    dy: '1,15%',
    precoTeto: 'R$ 11,90',
    viesAtual: 'Compra',
    variacaoHoje: '+0.5%',
    rendProventos: '+3.2%',
    ibovespaEpoca: '102.800',
    ibovespaVariacao: '+41.8%',
    percentualCarteira: '1.8%',
    marketCap: 'R$ 890M',
    pl: '12.8',
    pvp: '0.5',
    roe: '4.1%',
    relatorios: [
      { nome: 'Relatório Anual 2023', data: '2024-03-11', url: '#' },
    ],
    proventos: [
      { tipo: 'Dividendo', valor: 'R$ 0,05', dataEx: '15/02/2025', dataPagamento: '28/02/2025', status: 'Aprovado' },
    ]
  },
  'YDUQ3': {
    ticker: 'YDUQ3',
    nomeCompleto: 'Yduqs Participações S.A.',
    setor: 'Educação',
    descricao: 'Grupo educacional com foco em ensino superior presencial e a distância.',
    avatar: 'https://www.ivalor.com.br/media/emp/logos/YDUQ.png',
    precoAtual: 'R$ 15,54',
    variacao: '-42.8%',
    tendencia: 'down',
    dataEntrada: '11/11/2020',
    precoIniciou: 'R$ 27,16',
    dy: '2,64%',
    precoTeto: 'R$ 15,00',
    viesAtual: 'Compra',
    variacaoHoje: '-0.8%',
    rendProventos: '+8.5%',
    ibovespaEpoca: '110.500',
    ibovespaVariacao: '+31.8%',
    percentualCarteira: '3.5%',
    marketCap: 'R$ 5,2 bi',
    pl: '14.2',
    pvp: '1.1',
    roe: '7.8%',
    relatorios: [
      { nome: 'Relatório Anual 2023', data: '2024-03-19', url: '#' },
    ],
    proventos: [
      { tipo: 'Dividendo', valor: 'R$ 0,41', dataEx: '15/03/2025', dataPagamento: '30/03/2025', status: 'Aprovado' },
    ]
  },
  'SIMH3': {
    ticker: 'SIMH3',
    nomeCompleto: 'Simpar S.A.',
    setor: 'Logística',
    descricao: 'Holding com participações em empresas de logística e movimentação de cargas.',
    avatar: 'https://www.ivalor.com.br/media/emp/logos/SIMH.png',
    precoAtual: 'R$ 4,70',
    variacao: '-41.1%',
    tendencia: 'down',
    dataEntrada: '03/12/2020',
    precoIniciou: 'R$ 7,98',
    dy: '0,00%',
    precoTeto: 'R$ 10,79',
    viesAtual: 'Compra',
    variacaoHoje: '+0.2%',
    rendProventos: '+2.1%',
    ibovespaEpoca: '119.200',
    ibovespaVariacao: '+22.2%',
    percentualCarteira: '2.1%',
    marketCap: 'R$ 3,1 bi',
    pl: '25.8',
    pvp: '0.9',
    roe: '3.5%',
    relatorios: [
      { nome: 'Relatório Anual 2023', data: '2024-03-13', url: '#' },
    ],
    proventos: [
      { tipo: 'JCP', valor: 'R$ 0,00', dataEx: '15/04/2025', dataPagamento: '30/04/2025', status: 'Aprovado' },
    ]
  },
  'ALUP11': {
    ticker: 'ALUP11',
    nomeCompleto: 'Alupar Investimento S.A.',
    setor: 'Energia',
    descricao: 'Empresa de transmissão de energia elétrica e geração de energia renovável.',
    avatar: 'https://www.ivalor.com.br/media/emp/logos/ALUP.png',
    precoAtual: 'R$ 30,53',
    variacao: '+25.1%',
    tendencia: 'up',
    dataEntrada: '25/11/2020',
    precoIniciou: 'R$ 24,40',
    dy: '4,46%',
    precoTeto: 'R$ 29,00',
    viesAtual: 'Compra',
    variacaoHoje: '+1.8%',
    rendProventos: '+38.7%',
    ibovespaEpoca: '108.800',
    ibovespaVariacao: '+34.2%',
    percentualCarteira: '7.8%',
    marketCap: 'R$ 12,8 bi',
    pl: '12.5',
    pvp: '1.4',
    roe: '11.2%',
    relatorios: [
      { nome: 'Relatório Anual 2023', data: '2024-03-26', url: '#' },
    ],
    proventos: [
      { tipo: 'Dividendo', valor: 'R$ 1,36', dataEx: '15/05/2025', dataPagamento: '30/05/2025', status: 'Aprovado' },
    ]
  },
  'NEOE3': {
    ticker: 'NEOE3',
    nomeCompleto: 'Neoenergia S.A.',
    setor: 'Energia',
    descricao: 'Empresa de distribuição de energia elétrica
